SERVER_HOST = "192.168.0.34"
#SERVER_HOST = "10.0.0.1"
#SERVER_HOST = "localhost"
SERVER_PORT = 9000

DATA_DIR = "./data/"
HTTP_ROOT_FILE = "root_header.html"

HTTP_ROOT_FILE_PATH = DATA_DIR + HTTP_ROOT_FILE

USE_I2C_MATRIX = True

